### ISSUE TITLE
Can't build on Windows because of ncurses

### ISSUE THREAD

**Issue by kolumb** [tsoding/rcui#6]
This is an output of `cargo build`:
```
    Updating crates.io index
  Downloaded cc v1.0.61
  Downloaded libc v0.2.80
  Downloaded pkg-config v0.3.19
  Downloaded 3 crates (582.4 KB) in 3.20s
   Compiling pkg-config v0.3.19
   Compiling libc v0.2.80
   Compiling cc v1.0.61
   Compiling ncurses v5.99.0
error: failed to run custom build command for `ncurses v5.99.0`

Caused by:
  process didn't exit successfully: `c:\path\to\rcui\target\debug\build\ncurses-1da0815796c17bb2\build-script-build` (exit code: 101)
```

**Comment by et342** [comment]
Hello! I've been sitting on this for a while, but since the topic of cm, rcui and ncurses on Windows comes up often, it seems that I shouldn't wait anymore.

I've made Rust [bindings][pdcurses-rs] for PDCurses which are near drop-in substitute for [ncurses-rs] what means that, relative to ncurses, porting an application is almost as easy as sprinkling some `#[cfg(unix)]` and `#[cfg(windows)]` attributes here and there, e.g.
```rust
#[cfg(unix)]
use ncurses::*;
#[cfg(windows)]
use pdcurses::*;
```
and the rest of the code "should" "work" as is. 

There are, of course, minor behavioral differences between ncurses and pdcurses due to pdcurses quirks and the nature of Windows console, so additional adjustments are to be expected, but none of them should be too complicated.

As to why make another package if there is one [already][pdcurses-sys-bg] (which [pancurses] uses under the hood): reason is that existing package provides bindings to a [fork][pdcurses-mod] of PDCurses whose focus is on emulation of a terminal, i.e. an application won't be a tui application but a windowed one, spawned in a separate non-console window, pretending to be tui, what for me personally doesn't make much sense, although it probs was fine on older Windows where console was borked, but on newer one, console situation is better.

Also, although aforementioned fork, like original PDCurses, has flavors (and native Windows console is one of them, so no gui-tui), last time I tried, wincon flavor didn't support colors well and I unfortunately don't remember if there were other issues, but original PDCurses worked fine, so I picked original.

However, there seems to be some [work](https://github.com/Bill-Gray/PDCursesMod/commit/12859ec95ba17a6cc3129d7f6ae7e746190e4dac) is going on in a fork which touches on wincon flavor and since original seems to be inactive again, it may become or already is a better option but idk.

[pdcurses-rs]: https://github.com/et342/pdcurses-rs
[ncurses-rs]: https://github.com/jeaye/ncurses-rs
[pdcurses-sys-bg]: https://github.com/ihalila/pdcurses-sys
[pdcurses-mod]: https://github.com/Bill-Gray/PDCursesMod
[pancurses]: https://github.com/ihalila/pancurses

**Comment by rexim** [comment]
@et342 alright! Thanks for letting me know! I'm ok with using https://github.com/jeaye/ncurses-rs for this project.
